pipelines:
 - name: A_pipeline_6495_12
   steps:
    - name: S_A_pipeline_64952
      type: Bash
      execution:
        onExecute:
          - echo "hi"
        onComplete:
          - echo "state=pipeline2" > pipeline_state.txt
          - add_pipeline_files pipeline_state.txt pipeline_state_file
